name: Autograding Tests
"on":
    - repository_dispatch
    - push
permissions:
    checks: write
    actions: read
    contents: read
jobs:
    run-autograding-tests:
        runs-on: ubuntu-latest
        if: github.actor != 'github-classroom[bot]'
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Tests unitaires
              id: tests-unitaires
              uses: classroom-resources/autograding-python-grader@v1
              with:
                  timeout: 10
                  setup-command: pip install pytest
            - name: Autograding Reporter
              uses: classroom-resources/autograding-grading-reporter@v1
              env:
                  TESTS-UNITAIRES_RESULTS: "${{steps.tests-unitaires.outputs.result}}"
              with:
                  runners: tests-unitaires
